export const metadata = {
  title: 'Special Blog',
  description: 'Special Blog Page generated by me',
};

const specialBlog = () => {
  console.log('kaka');

  return (
    <div>
      <h2 className="text-2xl text-green-600 text-center">
        This is Special Blog
      </h2>
    </div>
  );
};

export default specialBlog;
