import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body suppressHydrationWarning={true}>
        <h2 className="text-3xl text-center p-5">Header</h2>
        {children}
        <h2 className="text-3xl text-center p-5">Footer</h2>
      </body>
    </html>
  );
}
